### ISSUE TITLE
部署后一片空白

### ISSUE THREAD

**Issue by vbskycn** [youshandefeiyang/tools#1]
部署后一片空白
请大佬指点一下

https://iptv-tools.pages.dev/

![image](https://github.com/youshandefeiyang/tools/assets/34542650/d40c115c-f597-4ede-bce6-e9f149ec2b21)

**Comment by youshandefeiyang** [comment]
指定目录为dist了没，应该是默认的

vbskycn ***@***.***> 于 2024年7月3日周三 14:07写道：
